---
# Apply hole configuration to all nodes, similar to top.sls, and running state.highstate
#
- name: apply configuration to all piston cloud switches
  hosts: all 
  user: root
  gather_facts: yes
  sudo: no

  roles:
      - common
      - interfaces 
