---
# Apply hole configuration to all nodes, similar to top.sls, and running state.highstate
#
- name: upgrade cumulus switches
  hosts: all 
  user: root 
  gather_facts: yes
  sudo: no

  vars:
      cl_version: 2.5.0

  roles:
      - upgrade_sw
      - common
