- name: configure timezone
  template: src=timezone.j2  dest=/etc/timezone
  notify: update timezone

#- name: copy cumulus license from main server
#  get_url:  url=ftp://license-server/cumulus.lic dest=/root/license_file

#- name: install cumulus license. Disruptive if license is going to be installed.
#  cl_license: src=/root/license_file restart_switchd=yes


