---
- hosts: spine
  user: cumulus
  sudo: True
  roles:
    - common
    - ospf_spine

- hosts: leaf
  user: cumulus
  sudo: True
  roles:
    - common
    - ospf_leaf

# Uncomment to demo switch upgrade
#- hosts: upgrade_sw
#  user: cumulus
#  sudo: True
#  roles:
#    - upgrade_sw

