# cl_version defined in upgrade_sw/vars/main.yml
- name: copy cumulus linux software to root partition.
  copy: src=CumulusLinux-{{cl_version}}-powerpc.bin dest=/root

- name : upgrade cumulus linux software.
  cl_img_install: src="/root/CumulusLinux-{{cl_version}}-powerpc.bin" switch_slot=yes
  register: reboot_switch

- name: reboot switch
  shell: reboot
  when: reboot_switch.changed == True

- name: wait for the switch to come back
  local_action: wait_for host=ansible_hostname port=22 state=stopped
  when: reboot_switch.changed == True

- name: wait for cumulus switch to boot and respond to port 22
  local_action: wait_for host=ansible_hostname port=22 delay=30
  when: reboot_switch.changed == True

